#!/usr/bin/env node
/* Builds every brand asset from brand/mark.mjs.
   Run:  node brand/build.mjs

   Writes, at the site root:  favicon.svg (follows the OS theme), favicon-32.png,
   apple-touch-icon.png, icon-192.png, icon-512.png, icon-maskable-512.png,
   og-image.png. In brand/: mark.svg, mark-dark.svg, logo-light.png,
   logo-dark.png, logo-light.svg, logo-dark.svg. For the two React apps:
   src/brand-mark.ts (the geometry) and the IMM platform's favicon.

   PNGs are rendered with Playwright's Chromium (element screenshots at exact
   pixel sizes; plain headless Chromium cannot open a window narrower than
   485px, which rules out a 32px favicon). */
import { writeFileSync, mkdirSync, readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { MARK, markElements } from './mark.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = (p, s) => { writeFileSync(join(root, p), s); console.log('  ' + p); };

// The palette, as literals: these files leave the site and cannot read its tokens.
const INK = '#14171C', PAPER = '#F4F3EF', DARK = '#0E1013', INK_D = '#EDEEF0', EU = '#2a78d6', EU_D = '#3987e5', MUTED = '#5b6068', MUTED_D = '#9aa0a8';

const svgMark = (ink, dot) => markElements(ink, dot);
const svgFile = (inner, extra = '') => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"${extra}>${inner}</svg>\n`;

console.log('brand assets:');
mkdirSync(join(root, 'brand'), { recursive: true });
out('brand/mark.svg', svgFile(svgMark(INK, EU)));
out('brand/mark-dark.svg', svgFile(svgMark(INK_D, EU_D)));
// The favicon follows the browser's colour scheme, so the leaf never disappears into a dark tab strip.
out('favicon.svg', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><style>.i{stroke:${INK}}.f{fill:${INK}}.d{fill:${EU}}@media (prefers-color-scheme:dark){.i{stroke:${INK_D}}.f{fill:${INK_D}}.d{fill:${EU_D}}}</style>${MARK.strokes.map(x => `<path class="i" d="${x.d}" fill="none" stroke-width="${x.w}" stroke-linecap="round" stroke-linejoin="round"/>`).join('')}${MARK.nodes.map(([x, y, r]) => `<circle class="f" cx="${x}" cy="${y}" r="${r}"/>`).join('')}<circle class="d" cx="${MARK.dot[0]}" cy="${MARK.dot[1]}" r="${MARK.dot[2]}"/></svg>\n`);

// The IMM platform ships its own favicon; the two React apps import the geometry.
out('platform-app/public/favicon.svg', readFileSync(join(root, 'favicon.svg'), 'utf8'));
const tsGeometry = `// Generated by brand/build.mjs from brand/mark.mjs — do not edit.
export const MARK = ${JSON.stringify(MARK)} as const;
`;
out('workspace-app/src/brand-mark.ts', tsGeometry);
out('platform-app/src/brand-mark.ts', tsGeometry);

/* Wordmark lockups as SVG use the Geist family by name; where Geist is not
   installed they fall back to system sans. The PNGs below embed the real font. */
const lockupSvg = dark => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 330 48" width="660" height="96"><g transform="translate(0 0) scale(1.5)">${svgMark(dark ? INK_D : INK, dark ? EU_D : EU)}</g><text x="60" y="33" font-family="Geist, 'Geist Variable', system-ui, sans-serif" font-size="27" letter-spacing="-0.8"><tspan font-weight="640" fill="${dark ? INK_D : INK}">ReGenesis</tspan><tspan font-weight="400" fill="${dark ? MUTED_D : MUTED}"> Impact</tspan></text></svg>\n`;
out('brand/logo-light.svg', lockupSvg(false));
out('brand/logo-dark.svg', lockupSvg(true));

/* ── PNGs ─────────────────────────────────────────────────────────────── */
let chromium;
for (const base of [root + '/', '/opt/node22/lib/node_modules/playwright/']) {
  try { ({ chromium } = createRequire(base)('playwright')); break; } catch {}
}
if (!chromium) { console.error('✗ Playwright not found — PNGs not rendered (SVGs above are written)'); process.exit(1); }

// Fonts are inlined as data URIs: a page built with setContent cannot load file:// fonts.
const font = (fam, file) => `@font-face{font-family:'${fam}';font-weight:100 900;src:url(data:font/woff2;base64,${readFileSync(join(root, 'fonts', file)).toString('base64')}) format('woff2')}`;
const FONTS = font('Geist Variable', 'geist-latin-wght-normal.woff2') + font('Geist Mono Variable', 'geist-mono-latin-wght-normal.woff2');
const icon = (px, { pad = 0.14, radius = 0 } = {}) => {
  const m = Math.round(px * (1 - 2 * pad));
  return `<div id="x" style="width:${px}px;height:${px}px;background:${DARK};border-radius:${radius * px}px;display:flex;align-items:center;justify-content:center"><svg width="${m}" height="${m}" viewBox="0 0 32 32">${svgMark(PAPER, EU_D)}</svg></div>`;
};
const lockup = dark => `<div id="x" style="display:inline-flex;align-items:center;gap:28px;padding:48px 60px;background:${dark ? DARK : PAPER}"><svg width="112" height="112" viewBox="0 0 32 32">${svgMark(dark ? INK_D : INK, dark ? EU_D : EU)}</svg><span style="font:400 76px 'Geist Variable';letter-spacing:-.035em;color:${dark ? MUTED_D : MUTED}"><b style="font-weight:640;color:${dark ? INK_D : INK}">ReGenesis</b> Impact</span></div>`;
const og = `<div id="x" style="width:1200px;height:630px;box-sizing:border-box;padding:72px 80px;background:${PAPER};display:flex;flex-direction:column;font-family:'Geist Variable';color:${INK}">
  <div style="display:flex;align-items:center;gap:18px"><svg width="64" height="64" viewBox="0 0 32 32">${svgMark(INK, EU)}</svg><span style="font-size:40px;letter-spacing:-.03em;color:${MUTED}"><b style="font-weight:640;color:${INK}">ReGenesis</b> Impact</span></div>
  <div style="margin-top:auto;font-size:68px;line-height:1.02;font-weight:640;letter-spacing:-.04em;max-width:960px">Climate disclosure, worked out in your browser.</div>
  <div style="margin-top:26px;display:flex;justify-content:space-between;align-items:flex-end;border-top:1px solid #dcdad3;padding-top:22px">
    <span style="font-size:24px;color:${MUTED}">ESRS · CSRD · IFRS S2 · AASB S2 · PCAF · GHG Protocol</span>
    <span style="font:500 20px 'Geist Mono Variable';letter-spacing:.02em">regenesisimpact.in</span>
  </div></div>`;

const b = await chromium.launch();
const shot = async (html, path) => {
  const p = await b.newPage({ viewport: { width: 1400, height: 900 }, deviceScaleFactor: 1 });
  await p.setContent(`<!doctype html><meta charset="utf-8"><style>${FONTS}body{margin:0;background:transparent}</style>${html}`, { waitUntil: 'load' });
  await p.evaluate(() => document.fonts.ready);
  await p.locator('#x').screenshot({ path: join(root, path), omitBackground: true });
  await p.close(); console.log('  ' + path);
};
try {
  await shot(icon(32, { pad: 0.04, radius: 0.22 }), 'favicon-32.png');
  await shot(icon(180, { pad: 0.16 }), 'apple-touch-icon.png');   // iOS rounds the corners itself
  await shot(icon(192, { pad: 0.16, radius: 0.22 }), 'icon-192.png');
  await shot(icon(512, { pad: 0.16, radius: 0.22 }), 'icon-512.png');
  await shot(icon(512, { pad: 0.24 }), 'icon-maskable-512.png');  // inside the 80% safe zone, full bleed
  await shot(lockup(false), 'brand/logo-light.png');
  await shot(lockup(true), 'brand/logo-dark.png');
  await shot(og, 'og-image.png');
} finally { await b.close(); }
