// Guide definitions — one crawlable page per framework × market question
// buyers actually search. Facts are pulled from knowledge/kb.json entries
// (kbIds) so guides stay consistent with what the AI says, and both update
// from one place. Add a guide here, run `node seo/build-guides.mjs`.

export const GUIDES = [
  {
    slug: 'esrs-csrd-reporting-guide',
    title: 'ESRS and CSRD — Practical Guide for European Reporters',
    description: 'Who is in scope after the Omnibus, how double materiality works, what EU Taxonomy Article 8 asks for, and where XBRL tagging actually stands.',
    tool: 'esrs', toolHash: 'esrs', toolLabel: 'Open the free ESRS tool',
    market: 'European Union',
    kbIds: ['esrs-001', 'esrs-002', 'esrs-003', 'esrs-004', 'esrs-005', 'esrs-006'],
    intro: 'The CSRD is the broadest sustainability reporting regime in force, and it moved twice in 2026: the Omnibus cut who has to file, and the revised ESRS cut how much they file. This guide covers who is in scope now, what double materiality changes about your assessment, how the EU Taxonomy Article 8 KPIs are actually computed, and why the XBRL tagging deadline you were quoted no longer exists.',
    faq: [
      ['Am I in scope for CSRD after the Omnibus?', 'An EU company is in scope only if it exceeds both 1,000 employees and EUR 450mn net turnover — the Omnibus made this an AND test, not an either/or. Non-EU parent groups are tested on EU-generated turnover above EUR 450mn.'],
      ['Which ESRS do I file against for FY2026?', 'ESRS Set 1, Delegated Regulation (EU) 2023/2772. The revised simplified standards were adopted on 3 July 2026 but apply to financial years beginning on or after 1 January 2027, so a FY2026 report is prepared under Set 1.'],
      ['Is my IFRS S2 materiality assessment enough for ESRS?', 'No. ESRS reports a topic material to people and the environment OR to the company; IFRS S2 covers only the second. The impact side has to be assessed separately, and every omitted topical standard needs a stated reason.'],
      ['Do I have to report the OpEx Taxonomy KPI?', 'Not necessarily. Delegated Regulation (EU) 2026/73 lets you omit the OpEx KPI where it is not material to your business model, disclosing only its total value and why it is not material. The same regulation lets you skip assessing any activity below 10% of a KPI, applied per KPI independently.'],
      ['When does XBRL tagging become mandatory?', 'There is no date. Mandatory tagging of the sustainability statement is suspended by Directive (EU) 2026/470, in force 18 March 2026, until the ESEF Delegated Regulation is amended to cover it — which requires ESMA technical standards that have not been drafted. Any vendor quoting you a resumption date is guessing.'],
      ['Does the value chain cap get my suppliers off the hook?', 'Partly. You cannot require a value chain company of 1,000 employees or fewer to provide more than the voluntary standard asks — but gross Scope 1, 2 and 3 emissions are carved out of that cap, so the emissions request survives it.'],
    ],
  },
  {
    slug: 'ifrs-s2-reporting-guide',
    title: 'IFRS S2 Climate Disclosure — Practical Guide',
    description: 'What IFRS S2 requires: the four pillars, Scope 1–3 rules, transition reliefs and how to build a compliant climate disclosure.',
    tool: 'issb', toolHash: 'issb', toolLabel: 'Build your IFRS S2 report free',
    market: 'Global',
    kbIds: ['issb-001', 'issb-002', 'issb-009'],
    intro: 'IFRS S2 is the ISSB’s climate disclosure standard, now adopted or being adopted in 30+ jurisdictions including Australia, Singapore and (via convergence) India. This guide covers what the standard actually asks for and how to produce a defensible first report.',
    faq: [
      ['Is Scope 3 mandatory under IFRS S2?', 'Yes — paragraph 29(a) requires Scope 1, 2 and 3 measured per the GHG Protocol, but a one-year transition relief lets first-time reporters omit Scope 3 in year one.'],
      ['How does IFRS S2 relate to TCFD?', 'IFRS S2 fully incorporates the TCFD architecture (Governance, Strategy, Risk Management, Metrics & Targets), so an existing TCFD report is the natural starting point.'],
      ['Do small companies need IFRS S2?', 'Only where a jurisdiction mandates it — thresholds vary by market (see the Australia and Singapore guides). Voluntary adoption still builds investor credibility.'],
    ],
  },
  {
    slug: 'aasb-s2-australia-climate-reporting',
    title: 'AASB S2 — Australia’s Mandatory Climate Reporting Explained',
    description: 'AASB S2 Group 1/2/3 thresholds, start dates, protected statements and assurance phasing for Australian entities.',
    tool: 'issb', toolHash: 'issb', toolLabel: 'Check your AASB S2 readiness free',
    market: 'Australia',
    kbIds: ['issb-003', 'assurance-006', 'climate-005'],
    intro: 'Australia’s Treasury Laws Amendment (Financial Market Infrastructure) Act made climate reporting mandatory, phased by entity size from 1 January 2025. Here is who reports when, and what auditors will expect.',
    faq: [
      ['Which group is my company in?', 'You meet a group if you satisfy any two of its three thresholds. Group 1: revenue ≥ A$500m, assets ≥ A$1bn, employees ≥ 500. Group 2: A$200m / A$500m / 250. Group 3: A$50m / A$25m / 100.'],
      ['What are protected statements?', 'Scope 3, scenario analysis and transition plan statements get a 3-year regime where only ASIC can take action — private litigation is barred for those disclosures.'],
      ['When is reasonable assurance required?', 'Assurance phases from limited (governance + Scope 1–2 first) to reasonable assurance over all climate disclosures for financial years commencing 1 July 2030.'],
    ],
  },
  {
    slug: 'brsr-core-assurance-india',
    title: 'BRSR & BRSR Core — India’s ESG Reporting and Assurance Rules',
    description: 'SEBI BRSR for the top 1,000 listed companies, BRSR Core assured KPIs, value-chain disclosures and how to prepare.',
    tool: 'issb', toolHash: 'issb', toolLabel: 'Draft your BRSR sections free',
    market: 'India',
    kbIds: ['issb-004', 'assurance-005', 'dd-005'],
    intro: 'SEBI’s Business Responsibility and Sustainability Report applies to India’s top 1,000 listed companies, and BRSR Core adds assured KPIs phasing from the top 150 toward the top 1,000. This guide summarises scope, the KPI set and the assurance requirement.',
    faq: [
      ['Who must file BRSR?', 'The top 1,000 listed entities by market capitalisation file BRSR with their annual report; smaller listed companies may adopt voluntarily.'],
      ['What does BRSR Core add?', 'A defined KPI subset — GHG intensity, water and energy footprint, waste, safety spend, gender pay metrics and more — that requires independent assurance on a phased schedule.'],
      ['Does BRSR cover the value chain?', 'Yes — SEBI introduced value-chain ESG disclosures for the top 250 companies on a comply-or-explain basis.'],
    ],
  },
  {
    slug: 'sgx-climate-reporting-singapore',
    title: 'Singapore Climate Reporting — SGX and MAS Requirements',
    description: 'SGX ISSB-aligned climate reporting timeline, MAS environmental risk management guidelines, and what Singapore companies must do.',
    tool: 'issb', toolHash: 'issb', toolLabel: 'Start your ISSB-aligned report free',
    market: 'Singapore',
    kbIds: ['issb-005', 'climate-010'],
    intro: 'Singapore moves listed issuers to mandatory ISSB-aligned climate reporting from FY2025, with large non-listed companies following from FY2027, while MAS expects financial institutions to manage environmental risk end-to-end. Here is the combined picture.',
    faq: [
      ['When does mandatory reporting start?', 'SGX-listed issuers report ISSB-aligned climate disclosures from FY2025; large non-listed companies (revenue ≥ S$1bn) from FY2027.'],
      ['What do the MAS ERM guidelines require?', 'Board-level accountability for environmental risk, integration into risk frameworks, scenario analysis and disclosure — for banks, insurers and asset managers.'],
      ['Is assurance required in Singapore?', 'Not yet mandated, but the regulatory roadmap strongly signals it — preparing evidence as if assurance applies is the low-regret move.'],
    ],
  },
  {
    slug: 'ghg-protocol-inventory-guide',
    title: 'GHG Protocol Inventory — How to Measure Scope 1, 2 and 3',
    description: 'Build a defensible greenhouse gas inventory: boundaries, emission factors, dual Scope 2 reporting and audit-trail expectations.',
    tool: 'ghg', toolHash: 'ghg', toolLabel: 'Calculate your GHG inventory free',
    market: 'Global',
    kbIds: ['ghg-001', 'ghg-006', 'ghg-009'],
    intro: 'Every climate disclosure regime builds on a GHG Protocol inventory. This guide covers the decisions that determine whether yours survives assurance: boundary choice, factor vintages, dual Scope 2 reporting and the audit trail.',
    faq: [
      ['What is the difference between location- and market-based Scope 2?', 'Location-based uses the grid-average factor where you consume electricity; market-based reflects your contracts (RECs, PPAs, green tariffs). The Scope 2 Guidance requires reporting both.'],
      ['Which emission factors should I use?', 'The most recent official set for your geography — e.g. India CEA for grid electricity, UK DEFRA for fuels and travel — and record the vintage of every factor.'],
      ['What do verifiers check first?', 'Factor vintages, unit conversions (GJ vs MWh), completeness of the entity list, and certificates behind any market-based claims.'],
    ],
  },
  {
    slug: 'scope-3-emissions-guide',
    title: 'Scope 3 Emissions — The 15 Categories Explained',
    description: 'Which Scope 3 categories matter for your sector, spend-based vs activity-based methods, and how to start measuring value-chain emissions.',
    tool: 'ghg', toolHash: 'ghg', toolLabel: 'Screen your Scope 3 categories free',
    market: 'Global',
    kbIds: ['ghg-002', 'dd-006', 'ghg-007'],
    intro: 'Scope 3 is usually 70–95% of a company’s footprint and the hardest part of any inventory. This guide maps the 15 GHG Protocol categories, shows where to start by sector, and explains how supplier engagement upgrades data quality over time.',
    faq: [
      ['Do I have to measure all 15 categories?', 'No — you must assess all 15 for relevance and justify exclusions. Most companies find 3–6 categories material.'],
      ['Spend-based or activity-based?', 'Start spend-based (EEIO factors × procurement spend) for coverage, then upgrade the biggest categories to activity- or supplier-specific data.'],
      ['When does SBTi require a Scope 3 target?', 'When Scope 3 is at least 40% of your total footprint — which is true for most non-extractive sectors.'],
    ],
  },
  {
    slug: 'pcaf-financed-emissions-guide',
    title: 'PCAF Financed Emissions — A Guide for Banks and Investors',
    description: 'How to measure portfolio emissions under the PCAF Standard: attribution, asset classes, data-quality scores and disclosure.',
    tool: 'ghg', toolHash: 'ghg', toolLabel: 'Estimate financed emissions free',
    market: 'Global',
    kbIds: ['ghg-003', 'ghg-002', 'climate-007'],
    intro: 'For financial institutions, category 15 (investments) dwarfs everything else. PCAF is the global standard for measuring it. This guide covers the attribution formula, the seven asset classes and the data-quality scoring that regulators increasingly expect.',
    faq: [
      ['What is the PCAF attribution formula?', 'Financed emissions = (your outstanding amount ÷ the company’s EVIC) × the company’s emissions — summed across the portfolio, by asset class.'],
      ['What are PCAF data quality scores?', 'A 1–5 scale per exposure (1 = audited reported emissions, 5 = economic-activity proxies); portfolios disclose the exposure-weighted average and improve it over time.'],
      ['Does PCAF cover sovereigns and mortgages?', 'Yes — PCAF v2 covers listed equity/bonds, business loans, project finance, commercial real estate, mortgages, motor vehicle loans and sovereign debt.'],
    ],
  },
  {
    slug: 'tcfd-scenario-analysis-guide',
    title: 'TCFD Scenario Analysis — How to Do It Properly',
    description: 'Choosing scenarios, quantifying transition and physical risk, and writing the resilience conclusion IFRS S2 expects.',
    tool: 'climate', toolHash: 'climate', toolLabel: 'Run scenario analysis free',
    market: 'Global',
    kbIds: ['climate-004', 'climate-001', 'climate-002'],
    intro: 'Scenario analysis is the part of climate reporting most companies fake and assurers increasingly test. This guide shows how to pick a defensible scenario set, quantify what matters and write the resilience statement IFRS S2 paragraph 22 requires.',
    faq: [
      ['How many scenarios do I need?', 'At least one aligned with ≤2°C. Good practice pairs three: an orderly transition, a disorderly one, and a hot-house physical-risk scenario.'],
      ['Which scenarios should financial institutions use?', 'NGFS scenarios are the supervisory default — they cover orderly (Net Zero 2050), disorderly (Delayed Transition) and hot-house (Current Policies) pathways with published carbon-price and damage variables.'],
      ['What goes in the resilience conclusion?', 'For each scenario: the material impacts on revenue, costs and assets by segment and time horizon, and what strategy changes (capex, hedging, exit) follow.'],
    ],
  },
  {
    slug: 'ngfs-climate-scenarios-explained',
    title: 'NGFS Climate Scenarios Explained — Net Zero to Hot House',
    description: 'The NGFS scenario families, what each assumes about carbon prices and warming, and how to use them in risk analysis.',
    tool: 'climate', toolHash: 'climate', toolLabel: 'Explore scenarios interactively',
    market: 'Global',
    kbIds: ['climate-001', 'climate-002', 'climate-003'],
    intro: 'The Network for Greening the Financial System scenarios are the shared language of climate risk for central banks, supervisors and reporters. This guide decodes the families and the variables you should actually pull out of them.',
    faq: [
      ['What is the difference between orderly and disorderly?', 'Orderly scenarios assume policy starts now and tightens smoothly; disorderly ones assume delay followed by an abrupt correction — same destination, much higher transition cost.'],
      ['What carbon price should I test?', 'Under Net Zero 2050, modelled prices reach roughly US$100–200/tCO2 by 2030 — apply them as shadow prices to Scope 1+2 to estimate earnings at risk.'],
      ['Which scenario has the worst physical risk?', 'Current Policies (hot-house): ~3°C warming by 2100, with chronic damages revised sharply upward in NGFS Phase V.'],
    ],
  },
  {
    slug: 'carbon-credits-buyers-guide',
    title: 'Carbon Credits Buyer’s Guide — Quality, Prices and Claims',
    description: 'How to buy credits that survive scrutiny: additionality, permanence, registries, price benchmarks and credible net-zero claims.',
    tool: 'credits', toolHash: 'credits', toolLabel: 'Browse verified credits',
    market: 'Global',
    kbIds: ['credits-001', 'credits-010', 'credits-004'],
    intro: 'The voluntary carbon market rewards buyers who understand quality and punishes those who don’t — regulators have pursued greenwashing claims built on weak offsets. This guide covers the quality tests, realistic price ranges and how credits fit a credible net-zero strategy.',
    faq: [
      ['What makes a credit high quality?', 'Demonstrated additionality, managed permanence (buffer pools), no leakage, robust MRV, and ideally an ICVCM Core Carbon Principles label.'],
      ['How much should credits cost?', 'Ranges vary hugely by type: REDD+ avoidance ~US$3–10/t, reforestation ~US$15–40/t, blue carbon ~US$20–40/t, durable removals US$100–600+/t. A too-cheap credit is a red flag.'],
      ['Can I use credits to claim net zero?', 'Only for residual emissions (5–10%) after deep reduction under SBTi’s Net-Zero Standard — and IFRS S2 requires disclosing your planned credit use and quality assumptions.'],
    ],
  },
  {
    slug: 'blue-carbon-credits-india',
    title: 'Blue Carbon Credits in India — Mangroves, Seagrass and Beyond',
    description: 'Why coastal ecosystems generate premium carbon credits and where India’s blue carbon opportunity is concentrated.',
    tool: 'credits', toolHash: 'credits', toolLabel: 'See blue carbon projects',
    market: 'India',
    kbIds: ['credits-003', 'credits-002', 'credits-008'],
    intro: 'Mangroves and seagrass meadows store carbon in sediment for centuries and shield coastlines while doing it — which is why blue carbon trades at a premium. India’s coastline holds some of the world’s largest restoration potential.',
    faq: [
      ['Why do blue carbon credits cost more?', 'Higher per-hectare sequestration, long-lived sediment storage, and stacked co-benefits (storm protection, fisheries, biodiversity) that corporate buyers value.'],
      ['Which methodology covers tidal wetlands?', 'Verra VM0033 is the principal tidal wetland and seagrass restoration methodology; Gold Standard also certifies blue carbon projects.'],
      ['Where is India’s blue carbon potential?', 'The Sundarbans, Tamil Nadu and Odisha coastlines, and the Andaman Islands — mangrove restoration belts and seagrass meadows.'],
    ],
  },
  {
    slug: 'sustainability-assurance-issa-5000',
    title: 'Sustainability Assurance & ISSA 5000 — Getting Audit-Ready',
    description: 'Limited vs reasonable assurance, the new ISSA 5000 standard, common findings and how to prepare your evidence pack.',
    tool: 'assurance', toolHash: 'assurance', toolLabel: 'Run a readiness scan free',
    market: 'Global',
    kbIds: ['assurance-001', 'assurance-002', 'assurance-007'],
    intro: 'Assurance is where sustainability reporting gets real: numbers must trace to evidence. With ISSA 5000 effective for periods from December 2026 and mandates phasing in across AU, IN and SG, this guide covers what practitioners test and how to be ready.',
    faq: [
      ['What is the difference between limited and reasonable assurance?', 'Limited assurance gives a negative-form conclusion from inquiry and analytics; reasonable assurance is audit-grade — controls testing, substantive detail and a positive opinion. Cost and evidence demands differ accordingly.'],
      ['What is ISSA 5000?', 'The IAASB’s comprehensive sustainability assurance standard (approved September 2024, effective for periods from 15 December 2026), applying to any framework and both assurance levels.'],
      ['What are the most common findings?', 'Stale emission factors, unit conversion errors, incomplete entity coverage, estimation presented as measurement, and market-based Scope 2 claims without certificates.'],
    ],
  },
];
