// Generated by brand/build.mjs from brand/mark.mjs — do not edit.
export const MARK = {"strokes":[{"d":"M16 3.2C24.8 8.4 27.2 19 16 28.8C4.8 19 7.2 8.4 16 3.2Z","w":2.2},{"d":"M16 28.8L16 11.5M16 22L22.6 16.6M16 22L9.4 16.6M16 15.5L21.4 10.4M16 15.5L10.6 10.4","w":1.8}],"nodes":[[16,22,1.9],[16,15.5,1.9]],"dot":[16,8.9,3.3]} as const;
